In this Notebook form the attribute table in QGIS I get latitude and longitud columns for baresoil samples. This points will be then used in GEE to extract their spectral bands imformation during 2015.

In [4]:
import pandas as pd

In [6]:
base_path = '/home/clara/Documents/'

In [15]:
lucas = pd.read_csv(f'{base_path}/autoencoders/bare_soil-detection/data/topsoil_2015.csv')
lucas

,Point_ID,Coarse,Clay,Sand,Silt,pH_CaCl2,pH_H20,EC,OC,CaCO3,...,LU,NUTS_0,NUTS_1,NUTS_2,NUTS_3,LC0_Desc,LC1_Desc,LU1_Desc,x,y
0,26581768,NaN,NaN,NaN,NaN,6.9,7.24,18.14,24.6,34,...,U111,PT,PT1,PT15,PT150,Grassland,Grassland without tree/shrub cover,Agriculture (excluding fallow land and kitchen...,-8.775252,37.139104
1,26581792,NaN,NaN,NaN,NaN,5.4,5.81,14.81,21.9,0,...,U410,PT,PT1,PT15,PT150,Shrubland,Shrubland without tree cover,Abandoned areas,-8.833728,37.349747
2,26581954,NaN,NaN,NaN,NaN,7.0,7.29,28.10,18.4,46,...,U112,PT,PT1,PT17,PT170,Grassland,Spontaneously re-vegetated surfaces,Fallow land,-9.242092,38.768531
3,26601784,NaN,NaN,NaN,NaN,4.4,5.17,5.37,48.0,0,...,U120,PT,PT1,PT15,PT150,Shrubland,Shrubland with sparse tree cover,Forestry,-8.792255,37.283972
4,26601978,NaN,NaN,NaN,NaN,7.1,7.38,21.60,25.2,0,...,U120,PT,PT1,PT17,PT170,Woodland,Broadleaved woodland,Forestry,-9.282250,38.982827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21854,64881666,15.0,50.0,23.0,27.0,6.7,6.97,21.10,8.4,1,...,U112,CY,CY0,CY00,CY000,Bareland,Other bare soil,Fallow land,33.907085,34.989242
21855,64901668,3.0,32.0,39.0,28.0,7.3,7.79,10.84,10.8,2,...,U420,CY,CY0,CY00,CY000,Grassland,Spontaneously re-vegetated surfaces,Semi-natural and natural areas not in use,33.933925,35.000901
21856,64901672,4.0,34.0,43.0,23.0,7.3,7.80,15.09,6.7,8,...,U111,CY,CY0,CY00,CY000,Cropland,Barley,Agriculture (excluding fallow land and kitchen...,33.945599,35.035389
21857,64961676,17.0,10.0,79.0,11.0,7.4,8.05,15.50,5.7,3,...,U420,CY,CY0,CY00,CY000,Grassland,Spontaneously re-vegetated surfaces,Semi-natural and natural areas not in use,34.020365,35.053061
21858,64981672,34.0,40.0,18.0,42.0,7.6,7.98,15.17,18.1,180,...,U420,CY,CY0,CY00,CY000,Shrubland,Shrubland without tree cover,Semi-natural and natural areas not in use,34.029660,35.012976

## delete columns with undesired data and delete rows different from LC0_Desc == Bareland

In [16]:
lucas.columns

Index(['Point_ID', 'Coarse', 'Clay', 'Sand', 'Silt', 'pH_CaCl2', 'pH_H20',
       'EC', 'OC', 'CaCO3', 'P', 'N', 'K', 'LC', 'LU', 'NUTS_0', 'NUTS_1',
       'NUTS_2', 'NUTS_3', 'LC0_Desc', 'LC1_Desc', 'LU1_Desc', 'x', 'y'],
      dtype='object')

- LC0_Desc = Land cover description (ex. bareland)
- LC1_Desc = more land cover description (ex. other baresoil, sand, rock and stones)
- LU1_Desc = Land Use description (ex. agriculture, fallow land, sport...)
- LC = F10: rock and stones, F40: other baresoil, F20: sand

In [17]:
drop = ['Coarse', 'Clay', 'Sand', 'Silt', 'pH_CaCl2', 'pH_H20',
       'EC', 'OC', 'CaCO3', 'P', 'N', 'K', 'LU', 'NUTS_0', 'NUTS_1',
       'NUTS_2', 'NUTS_3']

In [24]:
lucas_bareland = lucas.drop(drop, axis=1).loc[(lucas['LC0_Desc']=='Bareland')]
lucas_bareland

,Point_ID,LC,LC0_Desc,LC1_Desc,LU1_Desc,x,y
18,26841758,F40,Bareland,Other bare soil,Fallow land,-8.466693,37.108232
20,26841826,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,-8.630850,37.705463
36,27001936,F40,Bareland,Other bare soil,Fallow land,-8.726282,38.705168
49,27101940,F40,Bareland,Other bare soil,Fallow land,-8.624439,38.762267
89,27321784,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,-8.001415,37.439943
...,...,...,...,...,...,...,...
21766,57882508,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,28.474431,44.040401
21773,57922630,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,28.884681,45.092388
21778,57962548,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,28.688570,44.370723
21820,64161658,F40,Bareland,Other bare soil,Agriculture (excluding fallow land and kitchen...,33.126346,35.117963
21854,64881666,F40,Bareland,Other bare soil,Fallow land,33.907085,34.989242

In [25]:
lucas_bareland.to_csv(f'{base_path}/autoencoders/bare_soil-detection/data/baresoil_2015.csv')